Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ on:
       tag:
         description: 'Docker image tag for backend'
         required: true
-        default: 'latest'
+        default: 'neww'
         type: string
 
 jobs:
@@ -68,8 +68,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
       run: |
         cd Kubernetes-Manifests-file/Frontend
-        git fetch origin main
-        git rebase origin/main || (git rebase --skip && echo "Conflict skipped" || git rebase --abort)
+        git fetch origin master
+        git rebase origin/master || (git rebase --skip && echo "Conflict skipped" || git rebase --abort)
         
     - name: Update Deployment File
       env:
@@ -91,8 +91,8 @@ jobs:
         git add deployment.yaml
         git commit -m "Update deployment Image to version ${{ github.event.inputs.tag }}"
 
-        git pull --rebase origin main
-        git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:main
+        git pull --rebase origin master
+        git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:master
         
     - name: Cleanup Workspace
       run: |
